const urduDict = {
  blog: "بلاگ",
  summary: "خلاصہ",
  this: "یہ",
  is: "ہے",
  a: "ایک",
  test: "امتحان",
  example: "مثال",
  how: "کیسے",
  to: "کرنا",
  write: "لکھنا",
  clean: "صاف",
  code: "کوڈ",
  simple: "سادہ",
  principles: "اصول",
  programming: "پروگرامنگ",
  function: "فنکشن",
  variable: "متغیر",
  user: "صارف",
  input: "اندراج",
  output: "نتیجہ",
  language: "زبان",
  development: "ترقی",
  application: "ایپلیکیشن",
  web: "ویب",
  learn: "سیکھیں",
  learning: "سیکھنا",
  javascript: "جاوا اسکرپٹ",
  project: "پروجیکٹ",
  technology: "ٹیکنالوجی",
  computer: "کمپیوٹر",
  internet: "انٹرنیٹ",
  open: "کھلا",
  source: "ماخذ",
  software: "سافٹ ویئر",
  important: "اہم",
  fast: "تیز",
  slow: "سست",
  guide: "رہنما",
  tips: "مشورے",
  tricks: "چالاکیاں",
  best: "بہترین",
  for: "کے لیے",
  beginners: "نئے سیکھنے والے",
  advanced: "اعلی",
  concept: "تصور",
  method: "طریقہ",
  design: "ڈیزائن",
  system: "نظام",
  architecture: "فنِ تعمیر",
  performance: "کارکردگی",
  bug: "خرابی",
  error: "غلطی",
  fix: "درست کریں",
  secure: "محفوظ",
  backend: "بیک اینڈ",
  frontend: "فرنٹ اینڈ"
};


export function translateToUrdu(text) {
  return text
    .split(' ')
    .map(word => urduDict[word.toLowerCase()] || word)
    .join(' ');
}
